name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GoogleTest
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Debug – tree
        run: |
          echo "PWD = $(pwd)"
          ls -R

      - name: Build CLI
        run: g++ -std=c++17 -O2 -Wall -Wextra Assignment_1/ascii85.cpp Assignment_1/ascii85_cli.cpp -o ascii85

      # tests
      - name: Build tests
        run: g++ -std=c++17 -O2 -Wall -Wextra Assignment_1/ascii85.cpp Assignment_1/ascii85_test.cpp -lgtest_main -lgtest -lpthread -o ascii85_test

      - name: Run tests
        run: ./ascii85_test