name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GoogleTest
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build CLI
        working-directory: project          # ← путь к вашим исходникам
        run: g++ -std=c++17 -O2 -Wall -Wextra \
                 ascii85.cpp ascii85_cli.cpp -o ascii85


      - name: Build tests
        run: g++ -std=c++17 -O2 -Wall -Wextra \
                 ascii85.cpp ascii85_test.cpp \
                 -lgtest -lpthread -o ascii85_test

      - name: Run tests
        run: ./ascii85_test
